# Generated by Django 2.0 on 2020-02-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_ID', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('Rating', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('area_of_issue', models.CharField(blank=True, default=True, max_length=50, null=True)),
            ],
        ),
    ]
