# Generated by Django 2.2.2 on 2020-02-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='explanation',
            field=models.CharField(blank=True, default=True, max_length=200, null=True),
        ),
    ]
