# Generated by Django 2.2.2 on 2020-02-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0002_patient_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='area_of_issue',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='explanation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
