# Generated by Django 2.2.2 on 2020-02-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0003_auto_20200214_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('email', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
